openapi: 3.0.0
info:
  title: API Documentation
  description: API documentation for Users and Products
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/v1/user
    description: User API Base URL
  - url: http://localhost:5000/api/v1/product
    description: Product API Base URL
paths: {}
